### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by waytoomuchgaming** [MickeyPickey/TrackEverything#1]
Classic WoW english US client
Version: 1.7.2-release

4x TrackEverything\Locale\Locale.lua:234: attempt to index local 'L' (a nil value)
TrackEverything\Locale\Locale.lua:234: in main chunk

Locals:
_ = "TrackEverything"
ADDON_TABLE = <table> {
 ADDON_NAME = "Track Everything"
 ADDON_AUTHOR = "Mickeya @Gehennas-Alliance EU"
 Addon = <table> {
 }
 ADDON_VERSION = "1.7.2-release"
 ADDON_AUTHOR_GAME_INFO = "EU Gehennas (Mickeya), EU Firemaw (Miron, Bulbash). E-mail: sm.ownmail@gmail.com, Discord: Mickeya#9852, Battle.net: BULBASAUR#2352"
}
ADDON_NAME = "Track Everything"
L = nil
(*temporary) = <table> {
 apps = <table> {
 }
 GetLocale = <function> defined @BagSync\libs\AceLocale-3.0\AceLocale-3.0.lua:132
 NewLocale = <function> defined @BagSync\libs\AceLocale-3.0\AceLocale-3.0.lua:93
 appnames = <table> {
 }
}
(*temporary) = "Track Everything"
(*temporary) = "frFR"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'L' (a nil value)"

**Comment by MickeyPickey** [comment]
Hey! thx for the report. 
There was an issue in generated localization file. Should be fixed now, just rolled out an update, try this.
